In [11]:
list=[]
for i in range (2000 and 3210):
    if i%7==0 and i%5!=0:
        list.append(i)

In [26]:
def funct(n):
    
    
    if n==0:
        return 1
    else:
        return n*funct(n-1)

In [27]:
funct(6)

720

In [37]:
def funct(x):
    dic={}
    for i in range (1,x+1):
        dic[i]=i*i
    return dic 
print(funct(5))

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [43]:
def func(str,n):
    x=str[:n]
    y=str[n+1:]
    return x + y
func("ikram",3)

'ikrm'

In [49]:
import numpy as np
b=np.arange(6).reshape(2,3)
print(b.tolist())

[[0, 1, 2], [3, 4, 5]]


In [54]:
import numpy as np
x=np.array([0,1, 2])
y=np.array([2,1, 0])
print(x)
print(y)
print(np.cov(x,y))


[0 1 2]
[2 1 0]
[[ 1. -1.]
 [-1.  1.]]


In [ ]:
import math

numbers = input("Provide D: ")
numbers = numbers.split(',')

result_list = []
for D in numbers:
    Q = round(math.sqrt(2 * 50 * int(D) / 30))
    result_list.append(Q)

print(result_list)
